#!/usr/bin/env bun
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const canonicalLocalesDir = path.join(root, 'locales')
const desktopOutput = path.join(root, 'frontend', 'src', 'generated', 'locales.ts')
const androidResDir = path.join(root, 'mobile', 'android', 'src', 'main', 'res')
const androidHelperOutput = path.join(
  root,
  'mobile',
  'android',
  'src',
  'main',
  'java',
  'jp',
  'nonbili',
  'meron',
  'GeneratedIcuStrings.kt',
)
const iosOutput = path.join(root, 'mobile', 'ios', 'Meron', 'Localizable.xcstrings')

type Catalog = Record<string, string>
type Catalogs = Record<SupportedLocale, Catalog>
type LocaleTarget = { android: string; ios: string }
type Snapshot = Record<string, string | null>

const pluralCategories = ['zero', 'one', 'two', 'few', 'many', 'other'] as const
type PluralCategory = (typeof pluralCategories)[number]

const supportedLocales = [
  'ar',
  'de',
  'el',
  'en',
  'es',
  'et',
  'fr',
  'it',
  'ko',
  'lv',
  'pl',
  'pt',
  'pt_BR',
  'sv',
  'tr',
  'vi',
  'zh_Hans',
  'zh_Hant',
  'ja',
] as const
type SupportedLocale = (typeof supportedLocales)[number]

const languageNativeNames: Record<SupportedLocale, string> = {
  ar: 'العربية',
  de: 'Deutsch',
  el: 'Ελληνικά',
  en: 'English',
  es: 'Español',
  et: 'Eesti',
  fr: 'Français',
  it: 'Italiano',
  ko: '한국어',
  lv: 'Latviešu',
  pl: 'Polski',
  pt: 'Português',
  pt_BR: 'Português (Brasil)',
  sv: 'Svenska',
  tr: 'Türkçe',
  vi: 'Tiếng Việt',
  zh_Hans: '简体中文',
  zh_Hant: '繁體中文',
  ja: '日本語',
}

const localeMap: Partial<Record<SupportedLocale, LocaleTarget>> = {
  en: { android: 'values', ios: 'en' },
  pt_BR: { android: 'values-pt-rBR', ios: 'pt-BR' },
  zh_Hans: { android: 'values-b+zh+Hans', ios: 'zh-Hans' },
  zh_Hant: { android: 'values-b+zh+Hant', ios: 'zh-Hant' },
}

function main() {
  const command = process.argv[2]
  if (!command || !['validate', 'generate', 'check-generated'].includes(command)) {
    console.error('Usage: bun scripts/i18n/catalog.ts <validate|generate|check-generated>')
    process.exit(2)
  }

  const catalogs = readCanonicalCatalogs()
  validateCatalogs(catalogs)

  if (command === 'validate') return
  if (command === 'generate') {
    generateAll(catalogs)
    return
  }
  if (command === 'check-generated') {
    checkGenerated(catalogs)
  }
}

function readCanonicalCatalogs(): Catalogs {
  const catalogs = {} as Catalogs
  for (const locale of supportedLocales) {
    const file = path.join(canonicalLocalesDir, `${locale}.json`)
    if (!fs.existsSync(file)) {
      throw new Error(`Missing catalog: ${path.relative(root, file)}`)
    }
    catalogs[locale] = JSON.parse(fs.readFileSync(file, 'utf8'))
  }
  return catalogs
}

function validateCatalogs(catalogs: Record<string, Catalog>) {
  const enKeys = Object.keys(catalogs.en).sort()
  const enSet = new Set(enKeys)
  const enPlaceholders = placeholderMap(catalogs.en)
  for (const [locale, catalog] of Object.entries(catalogs)) {
    const keys = Object.keys(catalog).sort()
    const keySet = new Set(keys)
    const missing = enKeys.filter((key) => !keySet.has(key))
    const extra = keys.filter((key) => !enSet.has(key))
    if (missing.length || extra.length) {
      throw new Error(
        `${locale} key mismatch. Missing: ${missing.join(', ') || '(none)'}. Extra: ${extra.join(', ') || '(none)'}`,
      )
    }
    for (const [key, value] of Object.entries(catalog)) {
      if (typeof value !== 'string' || value.length === 0) {
        throw new Error(`${locale}.${key} must be a non-empty string`)
      }
      validateBalancedBraces(locale, key, value)
      const expected = enPlaceholders[key] ?? []
      const actual = placeholders(value)
      if (expected.join('\0') !== actual.join('\0')) {
        throw new Error(
          `${locale}.${key} placeholder mismatch. Expected {${expected.join(', ')}}, got {${actual.join(', ')}}`,
        )
      }
    }
  }
}

function generateAll(catalogs: Catalogs) {
  generateDesktop(catalogs)
  generateAndroid(catalogs)
  generateIos(catalogs)
}

function checkGenerated(catalogs: Catalogs) {
  const before = snapshotGenerated()
  generateAll(catalogs)
  const after = snapshotGenerated()
  const changed = Object.keys(after).filter((file) => before[file] !== after[file])
  if (changed.length) {
    throw new Error(
      `Generated localization files were stale: ${changed.map((file) => path.relative(root, file)).join(', ')}`,
    )
  }
}

function generateDesktop(catalogs: Catalogs) {
  ensureDir(path.dirname(desktopOutput))
  const body = `// Generated by scripts/i18n/catalog.ts. Do not edit by hand.
export const supportedI18nLanguages = ${JSON.stringify(supportedLocales, null, 2)} as const

export type SupportedI18nLanguage = (typeof supportedI18nLanguages)[number]

export const languageNativeNames: Record<SupportedI18nLanguage, string> = ${JSON.stringify(languageNativeNames, null, 2)}

export const messages: Record<SupportedI18nLanguage, Record<string, string>> = ${JSON.stringify(catalogs, null, 2)}
`
  fs.writeFileSync(desktopOutput, body)
}

function generateAndroid(catalogs: Catalogs) {
  const helperMessages = {} as Catalogs
  for (const [locale, catalog] of Object.entries(catalogs)) {
    const supportedLocale = locale as SupportedLocale
    const valuesDir = path.join(androidResDir, androidLocaleDir(supportedLocale))
    ensureDir(valuesDir)
    const simple = Object.entries(catalog).filter(([, value]) => !hasIcuPlaceholder(value))
    const lines = [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<resources>',
      '    <string name="app_name">Meron</string>',
    ]
    for (const [key, value] of simple) {
      lines.push(`    <string name="${androidName(key)}">${androidEscape(value)}</string>`)
    }
    lines.push('</resources>', '')
    fs.writeFileSync(path.join(valuesDir, 'strings.xml'), lines.join('\n'))

    helperMessages[supportedLocale] = Object.fromEntries(
      Object.entries(catalog).filter(([, value]) => hasIcuPlaceholder(value)),
    )
  }

  const kotlin = `// Generated by scripts/i18n/catalog.ts. Do not edit by hand.
package jp.nonbili.meron

internal val generatedIcuStrings: Map<String, Map<String, String>> = mapOf(
${Object.entries(helperMessages)
  .map(
    ([locale, messages]) => `    ${kotlinString(locale)} to mapOf(
${Object.entries(messages)
  .map(([key, value]) => `        ${kotlinString(key)} to ${kotlinString(value)},`)
  .join('\n')}
    ),`,
  )
  .join('\n')}
)

internal fun generatedIcuString(
    locale: String,
    key: String,
    args: Map<String, Any?> = emptyMap(),
): String {
    val messages = generatedIcuStrings[locale]
        ?: generatedIcuStrings[locale.substringBefore('-')]
        ?: generatedIcuStrings[locale.substringBefore('_')]
        ?: generatedIcuStrings["en"]
        ?: emptyMap()
    val template = messages[key] ?: generatedIcuStrings["en"]?.get(key) ?: key
    return formatGeneratedIcu(template, args)
}

private fun formatGeneratedIcu(
    template: String,
    args: Map<String, Any?>,
): String {
    val plural = parseGeneratedPlural(template)
    val selected = if (plural == null) template else {
        val count = (args[plural.argument] as? Number)?.toLong()
            ?: args[plural.argument]?.toString()?.toLongOrNull()
            ?: 0L
        plural.variants[if (count == 1L) "one" else "other"]
            ?: plural.variants["other"]
            ?: template
    }
    return replaceGeneratedPlaceholders(selected, args)
}

private data class GeneratedPlural(
    val argument: String,
    val variants: Map<String, String>,
)

private fun parseGeneratedPlural(template: String): GeneratedPlural? {
    val prefix = Regex("""^\\{([A-Za-z][A-Za-z0-9_]*)\\s*,\\s*plural\\s*,""").find(template) ?: return null
    var index = prefix.range.last + 1
    val variants = linkedMapOf<String, String>()
    while (index < template.lastIndex) {
        while (index < template.length && template[index].isWhitespace()) index += 1
        val categoryStart = index
        while (index < template.length && template[index].isLetter()) index += 1
        if (categoryStart == index) break
        val category = template.substring(categoryStart, index)
        while (index < template.length && template[index].isWhitespace()) index += 1
        if (index >= template.length || template[index] != '{') break
        val branch = readGeneratedBraceBranch(template, index)
        variants[category] = branch.first
        index = branch.second
    }
    return GeneratedPlural(prefix.groupValues[1], variants)
}

private fun readGeneratedBraceBranch(
    template: String,
    start: Int,
): Pair<String, Int> {
    var depth = 0
    var index = start
    while (index < template.length) {
        when (template[index]) {
            '{' -> depth += 1
            '}' -> {
                depth -= 1
                if (depth == 0) {
                    return template.substring(start + 1, index) to index + 1
                }
            }
        }
        index += 1
    }
    return template.substring(start + 1) to template.length
}

private fun replaceGeneratedPlaceholders(
    value: String,
    args: Map<String, Any?>,
): String =
    Regex("""\\{([A-Za-z][A-Za-z0-9_]*)\\}""").replace(value) { match ->
        args[match.groupValues[1]]?.toString().orEmpty()
    }
`
  fs.writeFileSync(androidHelperOutput, kotlin)
}

function generateIos(catalogs: Catalogs) {
  ensureDir(path.dirname(iosOutput))
  const strings: Record<
    string,
    { extractionState: 'manual'; localizations: Record<string, { stringUnit: { state: 'translated'; value: string } }> }
  > = {}
  for (const key of Object.keys(catalogs.en).sort()) {
    const localizations: Record<string, { stringUnit: { state: 'translated'; value: string } }> = {}
    for (const locale of supportedLocales) {
      localizations[iosLocale(locale)] = {
        stringUnit: {
          state: 'translated',
          value: catalogs[locale][key],
        },
      }
    }
    strings[key] = {
      extractionState: 'manual',
      localizations,
    }
  }
  fs.writeFileSync(
    iosOutput,
    `${JSON.stringify(
      {
        sourceLanguage: 'en',
        strings,
        version: '1.0',
      },
      null,
      2,
    )}\n`,
  )
}

function snapshotGenerated(): Snapshot {
  const files = [desktopOutput, androidHelperOutput, iosOutput]
  for (const locale of supportedLocales) {
    files.push(path.join(androidResDir, androidLocaleDir(locale), 'strings.xml'))
  }
  const out: Snapshot = {}
  for (const file of files) {
    out[file] = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null
  }
  return out
}

function flattenObject(value: Record<string, unknown>, prefix = ''): Catalog {
  const out: Catalog = {}
  for (const [key, item] of Object.entries(value)) {
    const nextKey = prefix ? `${prefix}.${key}` : key
    if (item && typeof item === 'object' && !Array.isArray(item)) {
      Object.assign(out, flattenObject(item, nextKey))
    } else if (typeof item === 'string') {
      out[nextKey] = item.replace(/\{\{\s*([A-Za-z0-9_]+)\s*\}\}/g, '{$1}')
    } else {
      throw new Error(`Unsupported catalog value at ${nextKey}`)
    }
  }
  return out
}

function foldPlurals(flat: Catalog): Catalog {
  const out: Catalog = {}
  const groups = new Map<string, Partial<Record<PluralCategory, string>>>()
  for (const [key, value] of Object.entries(flat)) {
    const match = key.match(/^(.*)_([a-z]+)$/)
    if (!match || !isPluralCategory(match[2])) {
      out[key] = value
      continue
    }
    const [, base, category] = match
    if (!groups.has(base)) groups.set(base, {})
    groups.get(base)[category] = value
  }

  for (const [base, variants] of groups) {
    if (!variants.other) {
      for (const [category, value] of Object.entries(variants)) out[`${base}_${category}`] = value
      continue
    }
    const categories = pluralCategories.filter((category) => variants[category])
    out[base] = `{count, plural, ${categories.map((category) => `${category} {${variants[category]}}`).join(' ')}}`
  }
  return out
}

function isPluralCategory(value: string): value is PluralCategory {
  return pluralCategories.includes(value as PluralCategory)
}

function placeholderMap(catalog: Catalog): Record<string, string[]> {
  return Object.fromEntries(Object.entries(catalog).map(([key, value]) => [key, placeholders(value)]))
}

function placeholders(value: string): string[] {
  const names = new Set<string>()
  for (const match of value.matchAll(/\{([A-Za-z][A-Za-z0-9_]*)\s*(?=[,}])/g)) {
    if (match[1] !== 'count') names.add(match[1])
  }
  return [...names].sort()
}

function validateBalancedBraces(locale: string, key: string, value: string) {
  let depth = 0
  for (const char of value) {
    if (char === '{') depth += 1
    if (char === '}') depth -= 1
    if (depth < 0) throw new Error(`${locale}.${key} has unbalanced braces`)
  }
  if (depth !== 0) throw new Error(`${locale}.${key} has unbalanced braces`)
}

function hasIcuPlaceholder(value: string) {
  return /\{[A-Za-z#]/.test(value)
}

function androidLocaleDir(locale: SupportedLocale) {
  return localeMap[locale]?.android ?? `values-${locale}`
}

function iosLocale(locale: SupportedLocale) {
  return localeMap[locale]?.ios ?? locale
}

function androidName(key: string) {
  return key
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toLowerCase()
}

function androidEscape(value: string) {
  let out = value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/'/g, "\\'")
    .replace(/%/g, '%%')
  if (/^[?@]/.test(out)) out = `\\${out}`
  return out
}

function kotlinString(value: string) {
  return JSON.stringify(value)
}

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true })
}

if (import.meta.main) {
  main()
}

export {
  androidEscape,
  androidLocaleDir,
  androidName,
  flattenObject,
  foldPlurals,
  iosLocale,
  placeholders,
  validateCatalogs,
}
