// Generates mobile/ui/src/commonMain/.../GeneratedStrings.kt from locales/*.json.
// One all-keys map (locale -> key -> ICU message) backing the Compose
// Multiplatform Localizer. Run: bun scripts/i18n/gen-compose-strings.ts
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..", "..");
const localesDir = join(root, "locales");
const out = join(
  root,
  "mobile/ui/src/commonMain/kotlin/jp/nonbili/meron/ui/GeneratedStrings.kt",
);

// Canonical file code -> app BCP-47 tag (underscore -> hyphen for script/region).
const tagFor = (code: string): string =>
  ({ pt_BR: "pt-BR", zh_Hans: "zh-Hans", zh_Hant: "zh-Hant" })[code] ?? code;

const esc = (s: string): string =>
  s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\$/g, "\\$")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");

const files = readdirSync(localesDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

// One function per locale keeps each JVM method well under the 64 KB bytecode
// limit (a single combined map initializer overflows it).
const fnName = (tag: string): string => "locale_" + tag.replace(/[^A-Za-z0-9]/g, "_");

let topEntries = "";
let fns = "";
for (const file of files) {
  const code = file.replace(/\.json$/, "");
  const tag = tagFor(code);
  const data = JSON.parse(readFileSync(join(localesDir, file), "utf8")) as Record<
    string,
    string
  >;
  topEntries += `    "${tag}" to ${fnName(tag)}(),\n`;
  fns += `private fun ${fnName(tag)}(): Map<String, String> =\n    buildMap {\n`;
  for (const key of Object.keys(data).sort()) {
    fns += `        put("${esc(key)}", "${esc(data[key])}")\n`;
  }
  fns += `    }\n\n`;
}

const kt = `// Generated by scripts/i18n/gen-compose-strings.ts. Do not edit by hand.
package jp.nonbili.meron.ui

internal val generatedStrings: Map<String, Map<String, String>> = mapOf(
${topEntries})

${fns}`;

writeFileSync(out, kt);
console.log(`Wrote ${out} (${files.length} locales)`);
